# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20171103_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='images',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
