# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 23:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='images',
            new_name='image',
        ),
    ]
